pexdrv:      драйвер создает файл усройства /dev/pexdrv0 и т.д. Придется изменить все приложения которые были построены по старой схеме.  Изменена обработка прерываний в согласованном режиме (работает правильно).  Доработан скрипт загрузки драйвера.  Добавлена цель install в Makefile драйвера.
common:    теперь  можно собирать отдельные библиотеки libboard.so, libpexboard.so. Пример использования библиотек в каталоге opencores/application/board_exam. Позволяет построитьуниверсальное тестовое приложение.  Немнго доработаны все классы. common/dma будет содержать реализацию буфера DMA в userspace. 

test_adm:     проверен на ввод данных. Добавлен файл конфигурации теста в каталог application/adm_test/bin. В него добавлена возможность собирать данные в файл для графического анализа программой ISVI.

Все мини тесты переработаны и по крайней мере собираются. Проверялись не все.

diff --git a/soft/linux/driver/pexdrv/insert b/soft/linux/driver/pexdrv/insert
--- a/soft/linux/driver/pexdrv/insert
+++ b/soft/linux/driver/pexdrv/insert
@@ -4,32 +4,69 @@
 # This script is loading modules in the kernel. 
 # 
 
-kernel=`uname -r | grep 2.6`
+status ()
+{
+   if [ $1 -eq 0 ] ; then
+       echo "[SUCCESS]"
+   else
+       echo "[FAILED]"
 
-if [ ${kernel} = "" ]
+       if [ $2 -eq 1 ] ; then
+           echo "... loading aborted."
+           exit 1
+       fi
+   fi
+}
+
+echo
+
+kernel=`uname -r | grep 2.4`
+
+if [ $kernel ]
     then
-	module=ambpex.o
+        module=pexdrv.o
         mname=${module%.o}
     else
         module=`find *.ko`
         mname=${module%.ko}
 fi
-module="pexdrv.ko"
 
-if [ ${module} = "" ]
+device=pexdrv
+mode="666"
+
+chmod 777 /dev/shm
+
+if [ ${module} ]
     then
-        echo No kernel module found. ${module}
-	exit
+        echo -n " Find ${module} module      : "
+        status $? 0
     else
-        echo Find ${module} - kernel module.
+        echo -n " Kernel module not found    : "
+        status 1 0
+        exit
 fi
 
-/sbin/insmod ./$module $* || exit 1
+was_loaded=`/sbin/lsmod | cut -c 1-6 | grep $device`
 
-sleep 1
+if [ ${was_loaded} ]
+    then
+        echo -n " Remove loaded module       : "
+        /sbin/rmmod $device
+        status $? 0
+    else
+        echo Loading module: ${module}
+fi
 
-devfiles=`ls /dev/* | grep AMB`
+echo -n " Loading pexdrv module      : "
+insmod ./${module}
 
-#echo ${devfiles}
+until [ -e /dev/pexdrv0 ]
+do
+    sleep 1.5
+done
 
-chmod -v 666 ${devfiles}
+chmod 666 /dev/pexdrv*
+
+status $? 0
+
+echo
